code_transform.class_new.variants:
  collection: collection
  default: default
  drupal-functional-test: drupal-functional-test
  drupal-kernel-test: drupal-kernel-test
  drupal-unit-test: drupal-unit-test
