{
  imports = [
    ./bluetuith.nix
    ./bookmarkthis.nix
    ./browsers/chromium.nix
    ./browsers/firefox.nix
    ./browsers/qutebrowser.nix
    ./dev-commit.nix
    ./direnv.nix
    ./flameshot.nix
    ./gnupg.nix
    ./gtk.nix
    ./media/handbrake.nix
    ./media/mpv.nix
    ./neovim
    ./node.nix
    ./phpactor
    ./ranger.nix
    ./redshift.nix
    ./screenkey.nix
    ./starship.nix
    ./sxhkd.nix
    ./zsh
  ];
}
