{
  imports = [
    ./cli/bluetuith.nix
    ./cli/bookmarkthis.nix
    ./cli/dev-commit.nix
    ./cli/direnv.nix
    ./cli/fzf.nix
    ./cli/git.nix
    ./cli/node.nix
    ./cli/notes.nix
    ./cli/ranger.nix
    ./cli/starship.nix
    ./cli/sxhkd.nix
    ./cli/tmux-sessionizer.nix
    ./cli/tmux.nix
    ./cli/zsh
    ./coding/neovim
    ./coding/phpactor
    ./core/gnupg.nix
    ./desktop/browsers/chromium.nix
    ./desktop/browsers/firefox.nix
    ./desktop/browsers/qutebrowser.nix
    ./desktop/flameshot.nix
    ./desktop/gtk.nix
    ./desktop/media/handbrake.nix
    ./desktop/media/makemkv.nix
    ./desktop/media/mpv.nix
    ./desktop/redshift.nix
    ./desktop/screenkey.nix
  ];
}
