{
  imports = [
    ./avahi.nix
    ./bluetooth.nix
    ./dconf.nix
    ./docker.nix
    ./dwm
    ./fonts.nix
    ./gitea-actions-runner.nix
    ./gnupg.nix
    ./kanata.nix
    ./media
    ./nix-index.nix
    ./nixpad
    ./openssh.nix
    ./password-store.nix
    ./pipewire.nix
    ./podman.nix
    ./st.nix
    ./thunar.nix
    ./xbanish.nix
    ./zram.nix
  ];
}
